### ISSUE TITLE
Select which example to use

### ISSUE THREAD

**Issue by tabrindle** [jormaechea/open-api-mocker#14]
First of all, thanks for writing this. Excellent library!

Currently the code selects the first index in an array of examples, and I'm looking into implementing some sort of selection mechanism, similar to your `Prefer` header for status codes. The use case being that some endpoints may give a variety of different responses for a 200, depending on user, role, or state. 

Implementation seems trivial and I will gladly fork and PR the change, however if you have a specific implementation in mind, I'd like your input. 

Decisions to make:
1. How to parse multiple options in Prefer header? Build on current implementation of match or do something else to accommodate n Prefer options?
2. Select example by name or index? Or either?
3. Anything else to consider?

Thanks in advance!

**Comment by jormaechea** [comment]
Hi @tabrindle, thanks for the issue!
Feel free to fork and PR..

About the design decisions to make:
1. The `Prefer` header is part of the [RFC7240](https://tools.ietf.org/html/rfc7240). I think it's time to use a more mature solution to parse it, for example the [parse-prefer-header npm package](https://www.npmjs.com/package/parse-prefer-header).
2. The `examples` property is a key-value object. Theoretically objects' properties are not ordered, so I'd discard the idea of selecting by index and implement selecting by name only.
3. I think this is quite straightforward (and useful). Please keep in mind to add unit tests for this to keep coverage level.

**Comment by tabrindle** [comment]
Awesome, I'll get started. 

Will use the above parse-prefer-header package if I can, will select examples by name, and add unit tests. Will close the issue once I have a PR open. 

Thanks!
