### ISSUE TITLE
Support for multiple files

### ISSUE THREAD

**Issue by jmamcallister** [jormaechea/open-api-mocker#16]
I'd like to specify a directory containing my definitions files and use it that way, is this possible?

**Comment by jormaechea** [comment]
Hi @jmamcallister, do you mean that you want to mock multiple API definitions?
The way to do so is launching one instance per API.

I do this for a microservice environment, where I mock each service on it's own docker. (I've developed a simple script that builds a `docker-compose.yml` file for me so I start all of them by just running `docker-compose up`).

Does this work for you? If not, what did you have in mind?

**Comment by jmamcallister** [comment]
Yes I mean multiple definitions each in their own file. I'll look into one container per definition, thanks!

**Comment by jormaechea** [comment]
Ok, I'll close the issue then.
If you need further assistance, get back and we reopen it.
