### ISSUE TITLE
Regression: Prefer:statusCode=XXX no longer works

### ISSUE THREAD

**Issue by fgnass** [jormaechea/open-api-mocker#17]
The return value from `parsePreferHeader` is `{ statuscode: '404' }` rather than `{ statusCode: '404' }` hence the following line does not pick it up correctly:
https://github.com/jormaechea/open-api-mocker/blame/7c0332c788f7af2f294fb6db46e3a75465f43e50/lib/mocker/express/server.js#L100

**Comment by jormaechea** [comment]
Released in v1.6.0 🚀
