### ISSUE TITLE
Does not support {camelCase} or multi path params

### ISSUE THREAD

**Issue by vinniejames** [jormaechea/open-api-mocker#3]
{camelCase} path params are not parsed correctly, nor are multiple params in the same path resulting in broken routes

**Comment by vinniejames** [comment]
Fix in server.js:

`normalizedPath = schemaUri.replace(/\{([a-zA-Z0-9]+)\}/g,`...

**Comment by jormaechea** [comment]
@vinniejames sorry, somehow I wasn't watching my own repo and didn't see this issue, nor the PR.. 

I run into the same issue, and today I released a patch to fix `multiple params` and `underscored_params`. `camelCase` ones already worked properly. (and also added test cases to avoid regression in the future). [CHANGELOG](https://github.com/jormaechea/open-api-mocker/blob/master/CHANGELOG.md)

Just released `v1.2.5`, please give it a try. I'll just close this issue and PR.

Sorry again for the delay, and thanks for contributing!
