### ISSUE TITLE
TypeError: this._checkContentType is not a function

### ISSUE THREAD

**Issue by bali182** [jormaechea/open-api-mocker#42]
Hello, I'm getting the error above, I'd like to ask for some help. I'm using a fairly simple schema, that can be found here:

https://github.com/bali182/oats/blob/master/projects/openapi-e2e-test/kitchenSink.json,

It has 1 operation, that looks like this, plus some schemas:
```json
{
  "/cat/dog": {
    "get": {
      "operationId": "getCatDog",
      "parameters": [
        {
          "in": "query",
          "schema": {
            "type": "string"
          },
          "name": "foo"
        }
      ],
      "responses": {
        "200": {
          "description": "foo",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/NamedSimpleObject"
              }
            }
          }
        }
      }
    }
  }
}
```

And starting the mock API programmatically here:

https://github.com/bali182/oats/blob/master/projects/openapi-e2e-test/src/utils/getMockServer.ts

I see in the logs that it recognized the operation, but then fails with above mentioned error. Full stack:

> [INFO ] Handling route GET /cat/dog
> [INFO ] Mocking API at http://localhost:3000/
> [INFO ] > [GET] /cat/dog?foo=test
> TypeError: this._checkContentType is not a function
>     at D:\Code\oats\common\temp\node_modules\.pnpm\open-api-mocker@1.7.1\node_modules\open-api-mocker\lib\mocker\express\request-handler.js:27:7     
>     at Layer.handle [as handle_request] (D:\Code\oats\common\temp\node_modules\.pnpm\express@4.17.1\node_modules\express\lib\router\layer.js:95:5)   
>     at next (D:\Code\oats\common\temp\node_modules\.pnpm\express@4.17.1\node_modules\express\lib\router\route.js:137:13)
>     at Route.dispatch (D:\Code\oats\common\temp\node_modules\.pnpm\express@4.17.1\node_modules\express\lib\router\route.js:112:3)
>     at Layer.handle [as handle_request] (D:\Code\oats\common\temp\node_modules\.pnpm\express@4.17.1\node_modules\express\lib\router\layer.js:95:5)   
>     at D:\Code\oats\common\temp\node_modules\.pnpm\express@4.17.1\node_modules\express\lib\router\index.js:281:22
>     at Function.process_params (D:\Code\oats\common\temp\node_modules\.pnpm\express@4.17.1\node_modules\express\lib\router\index.js:335:12)
>     at next (D:\Code\oats\common\temp\node_modules\.pnpm\express@4.17.1\node_modules\express\lib\router\index.js:275:10)
>     at rawParser (D:\Code\oats\common\temp\node_modules\.pnpm\body-parser@1.19.0\node_modules\body-parser\lib\types\raw.js:67:7)
>     at Layer.handle [as handle_request] (D:\Code\oats\common\temp\node_modules\.pnpm\express@4.17.1\node_modules\express\lib\router\layer.js:95:5)

Any clue if my schema is incorrect or it's something with the mock server?

**Comment by jormaechea** [comment]
@bali182 Just checked, it's indeed a bug.. Give me a couple of minutes to fix it.

**Comment by jormaechea** [comment]
@bali182 try upgrading to `v1.7.2`, it has been fixed there!

Thanks for the bug report!

**Comment by bali182** [comment]
Wow man that was the quickest response and fix :D Thank you!

**Comment by bali182** [comment]
And it indeed responds as expected, awesome!
