### ISSUE TITLE
Wrong locale is set for faker if locale string would be de-DE or en-EN.

### ISSUE THREAD

**Issue by ckruppe** [jormaechea/open-api-mocker#50]
Faker has lokale definitions that not all follow the ISO specifications. So de-DE definition for example is set with only 'de' not 'de_DE'.
I have an fix ready as pull request for you.

**Comment by Geertvdc** [comment]
I ran into the same problem. created a pr #54 to fix this.

**Comment by jormaechea** [comment]
Fix released in `v1.9.0`
