### ISSUE TITLE
Show example in documentation, but respond with faker data

### ISSUE THREAD

**Issue by Gennon** [jormaechea/open-api-mocker#53]
I have an issue where I want to provide an example for the documentation (when using Swagger UI), but I want the data the mock API responds with to be based on x-faker.

Schema:
```
"schemas": {
      "User": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "example": "John Doe",
            "x-faker": "{{name.firstName}} {{name.lastName}}"
          }
        }
     }
  }
```

The Schema above will only show the example data and not the faker data. But the documentation will show correct data ("John Doe").
However if I remove the example, then I get correct faker data, but the documentation will only show "string" because that is the type. 

Is it possible to change this method: https://github.com/jormaechea/open-api-mocker/blob/master/lib/response-generator/index.js#L40 to first check for x-faker instead of example? I guess that is where the issue is, but not sure.

**Comment by jormaechea** [comment]
Feature released in `v1.9.0`
