### ISSUE TITLE
Let x-faker override example

### ISSUE THREAD

**Issue by larsgraedig** [jormaechea/open-api-mocker#59]
We're having the following situation:

Property `name` has an `example` and an `x-faker` extension. This leads to open-api-mocker giving example the higher priority. Therefore repetitions of that element via `x-count` in an array all have "Desert Safari" as value.

![image](https://user-images.githubusercontent.com/24800158/168093107-e8ff313c-672f-4ecd-a509-4651716c3f08.png)

Now it would be nice to be able to tell open-api-mocker to give `x-faker` the higher priority in order to have different value for each element.

As soon as we remove `example` it works like this - however we want to have the example value in the OpenAPI spec as well for documentation reasons.

Do you see any way to toggle the behaviour via command line switch for instance?

**Comment by jormaechea** [comment]
I'm currently planning v2, which will include a bunch of breaking changes.. I think that preferring x-faker is a better default than the current one, so if you can move the PR to the `roadmap/v2` target branch, this can be accepted as is.

Thanks @larsgraedig!

**Comment by larsgraedig** [comment]
Hi @jormaechea,
happy to hear that - I've changed the PR accordingly. Looking forward to v2!

**Comment by jormaechea** [comment]
Merged to v2! 🎉

**Comment by jormaechea** [comment]
Merged into v2! 🎉
