### ISSUE TITLE
Handle patch versions

### ISSUE THREAD

**Issue by sdavids** [jormaechea/open-api-mocker#6]
> [FATAL] Error while validating schema: Expected a value of type `literal: "3.0.0"` but received `"3.0.3"`. in openapi

You might want to allow patch versions.

https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string

https://github.com/semver/semver/issues/232#issuecomment-546728483

**Comment by jormaechea** [comment]
Yeap, that's true.. I’ll fix that soon.

**Comment by jormaechea** [comment]
@sdavids Released in v1.3.1
