### ISSUE TITLE
Consider replacing faker with @faker-js/faker

### ISSUE THREAD

**Issue by EdwardSalter** [jormaechea/open-api-mocker#62]
Since the faker package is no longer maintained after the maintainer went rogue and [purposefully sabotaged it](https://www.bleepingcomputer.com/news/security/dev-corrupts-npm-libs-colors-and-faker-breaking-thousands-of-apps/), I'd suggest switching over to the "official" replacement version which is _@faker-js/faker_ (see the blog post [here](https://fakerjs.dev/about/announcements/2022-01-14.html)).
In doing so, we'll be open to getting the new features that exist in the new library and reduce the risk of accidentally upgrading to _faker@6.6.6_ which is the malicious version.

I am certainly happy to pick up this issue, ideally after #61 gets to avoid conflicts.

**Comment by jormaechea** [comment]
Sounds good. #61 has been merged now. Let's get this done 🚀
