### ISSUE TITLE
New release with updated Faker

### ISSUE THREAD

**Issue by jezzdk** [jormaechea/open-api-mocker#68]
Could we maybe get a tagged released of the `roadmap/v2` branch? It has the updated version of Faker which would be quite useful, for me at least :)

**Comment by jormaechea** [comment]
Hi @jezzdk!

Couldn't pay much attention to open source lately, but I've just published V2! 🚀 
Give it a try and let me know..

PS. Updated to faker@8 so double check breaking changes!
