### ISSUE TITLE
Can I mock error?

### ISSUE THREAD

**Issue by razb-viola** [jormaechea/open-api-mocker#77]
Can I get the error from the API? 

The API for example may return response of 200, 201 or 400. Can I mock the 201 and 400 as well?

Thanks.

**Comment by jormaechea** [comment]
Hi @razb-viola 
Yes, you can choose which response example you want to receive using the `Prefer` header.

See the example from the README:
> Response selection using request header: Prefer: statusCode=XXX or Prefer: example=name

**Comment by razb-viola** [comment]
Thanks that worked.
