### ISSUE TITLE
Array of length 1 parsed as a string

### ISSUE THREAD

**Issue by pownkel** [jormaechea/open-api-mocker#81]
My OpenApi spec contains an endpoint with a query parameter defined as follows:
```json
{
  "name": "expand",
  "required": false,
  "in": "query",
  "schema": {
    "type": "array",
    "items": {
    "type": "string",
    "enum": [
      "additionalFields"
    ]
  }
}
```

The parameter is defined as an array, but there is currently only one accepted enum value, so if this parameter is provided it must be an array of length 1. When I make a request to this endpoint through the generated swagger page, the URL is `https://baseurl.com/path?expand=additionalFields`.

However, if I try to make this request to the mocked server (with version 2.0.0), I get a 400 response, with the error `Invalid query param expand. Expected value of type array but received 'additionalFields'`. It seems that the value gets parsed as a string, with no room to interpret it as an array instead.

**Comment by jormaechea** [comment]
Hi @pownkel. I believe that the issue is in the OpenAPI definition. The `expand` parameter is declared as an array of strings. It should be declared as a string with the enum.

Try removing the type array an items and it should work as expected.

```
{
  "name": "expand",
  "required": false,
  "in": "query",
  "schema": {
    "type": "string",
    "enum": [
      "additionalFields"
    ]
  }
}
```

**Comment by jormaechea** [comment]
If it's supposed to be an array, then you should make the request as `?expand[]=additionalFields` or `?expand[0]=additionalFields`, I don't recall which of them right now.

**Comment by pownkel** [comment]
Ah you're right, the syntax should be `expand[]` but we had a bug on our end that was preventing the API from accepting that. Closing this issue.
